load ./fwd-model/framework.maude

load ./rev-model/entity-with-key.maude

load framework.maude

load full-maude31.maude
load code-manipulation-mod-expr.maude


set show command off .
set show advisories off .
set show loop stats off .

(show module CODE-MANIPULATION[SEM_ENTITIES, 'X] .)
quit

*** load ../erlang-model/framework.maude
*** load framework.maude
*** (load-module('SEM_ENTITIES))
*** (transform-mod)
