mod SEM_ENTITY is
  protecting CINNI .

  sort Entity .

  *** Syntax definition
  sorts Guard Input .
  subsort Input < Guard .
  subsort Input < Entity .
  subsort Guard < Entity .


  op tau : -> Guard [ctor] .
  op _<_> : Chan Chan -> Guard [ctor prec 4] .
  op _(_) : Chan Qid -> Input [ctor prec 3] .

  sort Proc .
  subsort Proc < Entity .
  op !_._ : Input Proc -> Proc [ctor prec 6] .

  op emptyproc : -> Proc [ctor] .
  op _._ : Guard Proc -> Proc [ctor prec 5] .


endm
